CREATE TABLE [dbo].[DiscountOfferType](
	[DiscountOfferTypeId] [int] IDENTITY(1,1) NOT NULL,
	[DiscountOfferTypeName] [nvarchar](300) NULL,
 CONSTRAINT [PK_DiscountOfferType] PRIMARY KEY CLUSTERED 
(
	[DiscountOfferTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]