CREATE TYPE [dbo].[CustomerType] AS TABLE (
    [CustomerId]                   INT            NULL,
    [StoreId]                      INT            NOT NULL,
    [FirstName]                    NVARCHAR (100) NULL,
    [LastName]                     NVARCHAR (100) NULL,
    [Company]                      NVARCHAR (100) NULL,
    [CustomerCode]                 NVARCHAR (100) NULL,
    [CustomerGroupId]              INT            NULL,
    [IsLoyaltyEnabled]             BIT            NULL,
    [DateOfBirth]                  DATETIME       NULL,
    [Sex]                          NVARCHAR (10)  NULL,
    [Phone]                        NVARCHAR (20)  NULL,
    [Mobile]                       NVARCHAR (20)  NULL,
    [Fax]                          NVARCHAR (20)  NULL,
    [Email]                        NVARCHAR (50)  NULL,
    [Website]                      NVARCHAR (50)  NULL,
    [Twitter]                      NVARCHAR (50)  NULL,
    [IsCustomerOptedOutMail]       BIT            NULL,
    [PhysicalAddressStreet1]       NVARCHAR (200) NULL,
    [PhysicalAddressStreet2]       NVARCHAR (200) NULL,
    [PhysicalSuburb]               NVARCHAR (100) NULL,
    [PhysicalCity]                 NVARCHAR (100) NULL,
    [PhysicalPostcode]             NVARCHAR (50)  NULL,
    [PhysicalState]                NVARCHAR (50)  NULL,
    [PhysicalCountryId]            INT            NULL,
    [IsPostalAddSameAsPhysicalAdd] BIT            NULL,
    [PostalAddressStree1]          NVARCHAR (200) NULL,
    [PostalAddressStreet2]         NVARCHAR (200) NULL,
    [PostalSuburb]                 NVARCHAR (100) NULL,
    [PostalCity]                   NVARCHAR (100) NULL,
    [PostalPostCode]               NVARCHAR (50)  NULL,
    [PostalState]                  NVARCHAR (50)  NULL,
    [PostalCountryId]              INT            NULL);

