CREATE TYPE [dbo].[StoreSetup] AS TABLE (
    [StoreName]                            NVARCHAR (100) NOT NULL,
    [StoreURL]                             NVARCHAR (100) NULL,
    [DefaultCurrencyId]                    INT            NULL,
    [TimeZoneId]                           INT            NULL,
    [DisplayPricesId]                      INT            NULL,
    [SKUGenerationId]                      INT            NULL,
    [CurrentSequenceNumber]                NVARCHAR (100) NULL,
    [UserSwitchingSecurityId]              INT            NULL,
    [IsDiscountAllowedOnReceipt]           BIT            NULL,
    [IsOutOfStockEmailNotificationAllowed] BIT            NULL,
    [IsTipsOrSurchargeAllowed]             BIT            NULL,
    [IsLaybyAllowed]                       BIT            NULL,
    [IsOnAccountSaleAllowed]               BIT            NULL,
    [ContactFirstName]                     NVARCHAR (100) NULL,
    [ContactLastName]                      NVARCHAR (100) NULL,
    [Email]                                NVARCHAR (50)  NULL,
    [PhoneNumber]                          NVARCHAR (20)  NULL,
    [Website]                              NVARCHAR (50)  NULL,
    [TwitterHandle]                        NVARCHAR (50)  NULL,
    [FaceBook]                             NVARCHAR (50)  NULL,
    [LinkedIn]                             NVARCHAR (50)  NULL,
    [PhysicalAddressStreet1]               NVARCHAR (200) NULL,
    [PhysicalAddressStreet2]               NVARCHAR (200) NULL,
    [PhysicalSuburb]                       NVARCHAR (50)  NULL,
    [PhysicalCity]                         NVARCHAR (50)  NULL,
    [PhysicalPostcode]                     NVARCHAR (20)  NULL,
    [PhysicalState]                        NVARCHAR (50)  NULL,
    [PhysicalCountryId]                    INT            NULL,
    [IsPostalAddressSameAsPhysicalAddress] BIT            NULL,
    [PostalAddressStreet1]                 NVARCHAR (200) NULL,
    [PostalAddressStreet2]                 NVARCHAR (200) NULL,
    [PostalSuburb]                         NVARCHAR (50)  NULL,
    [PostalCity]                           NVARCHAR (50)  NULL,
    [PostalPostCode]                       NVARCHAR (20)  NULL,
    [PostalState]                          NVARCHAR (50)  NULL,
    [PostalCountryId]                      INT            NULL,
    [CreatedBy]                            INT            NULL,
    [CreatedOn]                            DATETIME       NULL,
    [UpdatedBy]                            INT            NULL,
    [UpdatedOn]                            DATETIME       NULL);

