//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountOfferStoreOutlet
    {
        public int DiscountOfferStoreOutletId { get; set; }
        public int DiscountOfferId { get; set; }
        public int StoreOutletId { get; set; }
    
        public virtual DiscountOffer DiscountOffer { get; set; }
        public virtual StoreOutlet StoreOutlet { get; set; }
    }
}
