//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNDEntities1 : DbContext
    {
        public DNDEntities1()
            : base("name=DNDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<CustomerGroupMaster> CustomerGroupMasters { get; set; }
        public virtual DbSet<DealnDonePlan> DealnDonePlans { get; set; }
        public virtual DbSet<DiscountOffer> DiscountOffers { get; set; }
        public virtual DbSet<DiscountOfferCustomer> DiscountOfferCustomers { get; set; }
        public virtual DbSet<DiscountOfferStoreOutlet> DiscountOfferStoreOutlets { get; set; }
        public virtual DbSet<DiscountOfferType> DiscountOfferTypes { get; set; }
        public virtual DbSet<DiscountType> DiscountTypes { get; set; }
        public virtual DbSet<DiscountTypeData> DiscountTypeDatas { get; set; }
        public virtual DbSet<DisplayPrice> DisplayPrices { get; set; }
        public virtual DbSet<DNDUser> DNDUsers { get; set; }
        public virtual DbSet<LabelPrinterFormat> LabelPrinterFormats { get; set; }
        public virtual DbSet<PricingTier> PricingTiers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductBrand> ProductBrands { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductInventory> ProductInventories { get; set; }
        public virtual DbSet<ProductSupplier> ProductSuppliers { get; set; }
        public virtual DbSet<ProductTag> ProductTags { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ProductVariant> ProductVariants { get; set; }
        public virtual DbSet<ProductVariantAttribute> ProductVariantAttributes { get; set; }
        public virtual DbSet<ProductVariantAttributeMaster> ProductVariantAttributeMasters { get; set; }
        public virtual DbSet<PurchaseStockOrder> PurchaseStockOrders { get; set; }
        public virtual DbSet<RegisterOpenCloseStatusType> RegisterOpenCloseStatusTypes { get; set; }
        public virtual DbSet<ReturnStockOrder> ReturnStockOrders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleManagement> RoleManagements { get; set; }
        public virtual DbSet<SalesTax> SalesTaxes { get; set; }
        public virtual DbSet<SellOpenCloseRegister> SellOpenCloseRegisters { get; set; }
        public virtual DbSet<SetupAccount> SetupAccounts { get; set; }
        public virtual DbSet<SetupAccountClearOutData> SetupAccountClearOutDatas { get; set; }
        public virtual DbSet<SetupContactInformation> SetupContactInformations { get; set; }
        public virtual DbSet<SetupGeneralStoreSetting> SetupGeneralStoreSettings { get; set; }
        public virtual DbSet<SetupLoyaltyPointsId> SetupLoyaltyPointsIds { get; set; }
        public virtual DbSet<SetupPaymentType> SetupPaymentTypes { get; set; }
        public virtual DbSet<SetupRegistersAskForNote> SetupRegistersAskForNotes { get; set; }
        public virtual DbSet<SetupRegistersCashManagement> SetupRegistersCashManagements { get; set; }
        public virtual DbSet<SetupRegistersReceiptTemplate> SetupRegistersReceiptTemplates { get; set; }
        public virtual DbSet<SetupSalesTaxGroupId> SetupSalesTaxGroupIds { get; set; }
        public virtual DbSet<SetupSalesTaxGroupMaster> SetupSalesTaxGroupMasters { get; set; }
        public virtual DbSet<SetupStoreAddress> SetupStoreAddresses { get; set; }
        public virtual DbSet<SKUGenerationType> SKUGenerationTypes { get; set; }
        public virtual DbSet<StockOrderStatu> StockOrderStatus { get; set; }
        public virtual DbSet<StockOrderType> StockOrderTypes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreOutlet> StoreOutlets { get; set; }
        public virtual DbSet<StoreOutletRegister> StoreOutletRegisters { get; set; }
        public virtual DbSet<StoreUser> StoreUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
        public virtual DbSet<TransferStockOrder> TransferStockOrders { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserSwitchingSecurityType> UserSwitchingSecurityTypes { get; set; }
        public virtual DbSet<ProductOutletPricing> ProductOutletPricings { get; set; }
        public virtual DbSet<ProductPricing> ProductPricings { get; set; }
    }
}
