//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPricing
    {
        public Nullable<int> ProductPricingId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<int> PricingTierId { get; set; }
        public Nullable<decimal> SupplyPrice { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> ProductPriceExcludingTax { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual PricingTier PricingTier { get; set; }
        public virtual Product Product { get; set; }
    }
}
