//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventory
    {
        public int ProductInventoryId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> ProductVariantId { get; set; }
        public string ProductVariantName { get; set; }
        public string ProductVariantSKU { get; set; }
        public string ProductVariantSupplierCode { get; set; }
        public Nullable<int> StoreOutletId { get; set; }
        public Nullable<int> StoreOutletCurrentInventory { get; set; }
        public Nullable<int> StoreOutletReorderPoint { get; set; }
        public Nullable<int> StoreOutletReorderAmount { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
