//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductInventoryAndTaxes = new HashSet<ProductInventoryAndTax>();
            this.ProductPricings = new HashSet<ProductPricing>();
            this.ProductTags = new HashSet<ProductTag>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductHandle { get; set; }
        public string Description { get; set; }
        public int ProductTypeId { get; set; }
        public int ProductBrandId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierCode { get; set; }
        public string SalesAccountCode { get; set; }
        public string PurchaseAccountCode { get; set; }
        public bool IsProductCanBeSold { get; set; }
        public decimal ProductLoyalty { get; set; }
        public bool IsActive { get; set; }
        public int StoreId { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsProductHasVariants { get; set; }
    
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductSupplier ProductSupplier { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInventoryAndTax> ProductInventoryAndTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPricing> ProductPricings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTag> ProductTags { get; set; }
    }
}
