//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryAndTax
    {
        public int ProductInventoryAndTaxId { get; set; }
        public int ProductId { get; set; }
        public string ProductSKU { get; set; }
        public bool IsProductHasVariants { get; set; }
        public Nullable<int> ProductVariantAttributeId { get; set; }
        public string ProductVariantAttributeValues { get; set; }
        public Nullable<int> InventoryOutletId { get; set; }
        public Nullable<int> CurrentInventoryCount { get; set; }
        public Nullable<int> ReorderPoint { get; set; }
        public Nullable<int> ReorderAmount { get; set; }
        public Nullable<int> SalesTaxId { get; set; }
        public Nullable<decimal> ProductOutletTaxRate { get; set; }
        public Nullable<decimal> ProductOutletTaxAmount { get; set; }
        public Nullable<decimal> ProductOutletRetailPrice { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductVariantAttribute ProductVariantAttribute { get; set; }
    }
}
