//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOutletPricing
    {
        public Nullable<int> ProductOutletPricingId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PricingTierId { get; set; }
        public Nullable<int> StoreOutletId { get; set; }
        public Nullable<int> SalestaxId { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> ProductPriceIncludingTax { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
