//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOpenCloseRegister
    {
        public int SellOpenCloseRegisterId { get; set; }
        public int StoreId { get; set; }
        public int LoggedInUserId { get; set; }
        public int LoggedInUserTypeId { get; set; }
        public int StoreOutletId { get; set; }
        public int StoreOutletRegisterId { get; set; }
        public int RegisterOpenCloseStatusTypeId { get; set; }
        public System.DateTime RegisterOpeningDateTime { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual RegisterOpenCloseStatusType RegisterOpenCloseStatusType { get; set; }
    }
}
