//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupGeneralStoreSetting
    {
        public int SetupGeneralStoreSettingsId { get; set; }
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StorePrivateURL { get; set; }
        public Nullable<int> DefaultCurrencyId { get; set; }
        public Nullable<int> TimeZoneId { get; set; }
        public Nullable<int> DisplayPricesId { get; set; }
        public Nullable<int> LabelPrinterFormatId { get; set; }
        public Nullable<int> SKUGenerationId { get; set; }
        public string CurrentSequenceNumber { get; set; }
        public Nullable<int> UserSwitchingSecurityId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual DisplayPrice DisplayPrice { get; set; }
        public virtual LabelPrinterFormat LabelPrinterFormat { get; set; }
        public virtual SKUGenerationType SKUGenerationType { get; set; }
        public virtual Store Store { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual UserSwitchingSecurityType UserSwitchingSecurityType { get; set; }
    }
}
