//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupAccountClearOutData
    {
        public int SetupAccountClearOutDataId { get; set; }
        public int SetupAccountId { get; set; }
        public Nullable<bool> IsClearSalesHistory { get; set; }
        public Nullable<bool> IsClearSalesHistoryAndProducts { get; set; }
        public Nullable<bool> IsClearCustomers { get; set; }
        public Nullable<bool> IsClearOutDataCompleted { get; set; }
        public Nullable<int> PlanSelectedId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual SetupAccount SetupAccount { get; set; }
    }
}
