//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupStoreAddress
    {
        public int SetupStoreAddressId { get; set; }
        public int StoreId { get; set; }
        public string PhysicalAddressStreet1 { get; set; }
        public string PhysicalAddressStreet2 { get; set; }
        public string PhysicalSuburb { get; set; }
        public string PhysicalCity { get; set; }
        public string PhysicalPostcode { get; set; }
        public string PhysicalState { get; set; }
        public Nullable<int> PhysicalCountryId { get; set; }
        public Nullable<bool> IsPostalAddressSameAsPhysicalAddress { get; set; }
        public string PostalAddressStreet1 { get; set; }
        public string PostalAddressStreet2 { get; set; }
        public string PostalSuburb { get; set; }
        public string PostalCity { get; set; }
        public string PostalPostCode { get; set; }
        public string PostalState { get; set; }
        public Nullable<int> PostalCountryId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
