//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOutlet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreOutlet()
        {
            this.ReturnStockOrders = new HashSet<ReturnStockOrder>();
            this.StoreOutletRegisters = new HashSet<StoreOutletRegister>();
            this.StoreUsers = new HashSet<StoreUser>();
            this.TransferStockOrders = new HashSet<TransferStockOrder>();
            this.TransferStockOrders1 = new HashSet<TransferStockOrder>();
        }
    
        public int StoreOutletId { get; set; }
        public int StoreId { get; set; }
        public string OutletName { get; set; }
        public Nullable<int> OutletDefaultSalesTaxId { get; set; }
        public string OutletOrderNumberPrefix { get; set; }
        public string OutletOrderNumber { get; set; }
        public string SupplierReturnPrefix { get; set; }
        public string SupplierReturnNumber { get; set; }
        public bool IsNegativeInventory { get; set; }
        public string PhysicalAddressStreet1 { get; set; }
        public string PhysicalAddressStreet2 { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> TimezoneId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string TwitterHandle { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnStockOrder> ReturnStockOrders { get; set; }
        public virtual SalesTax SalesTax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOutletRegister> StoreOutletRegisters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreUser> StoreUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferStockOrder> TransferStockOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferStockOrder> TransferStockOrders1 { get; set; }
    }
}
