//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupLoyaltyPointsId
    {
        public int SetupLoyaltyPointsId1 { get; set; }
        public int StoreId { get; set; }
        public Nullable<bool> DoEnableLoyaltyPoints { get; set; }
        public Nullable<decimal> SpendingAmountForLoyalty { get; set; }
        public Nullable<decimal> EarningAmountForLoyalty { get; set; }
        public Nullable<bool> DoOfferBonusLoyaltyPoints { get; set; }
        public Nullable<decimal> BonusLoyaltyAmount { get; set; }
        public Nullable<bool> IsShowWelcomeEmail { get; set; }
        public string LoyaltyWelcomEmailSubject { get; set; }
        public string LoyaltyWelcomEmailMessage { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
